In [3]:
import pandas as pd 
import numpy as np

In [4]:
# Things to do
# Map all routes in miami from buses and see how much area it covers
# Compare Miami vs other cities that have already adopted urban sensing
# Tableau map all the bus routes
# Compare the bus # vs the total car population and show %'s'
# What sensors can be useful in miami
# Solve situation, solution and sovergitny for Miami
# 20 century thinking vs 21 century thinking
# http://www.miamidade.gov/transit/WebServices/Transit_XML_Data_Feeds.pdf Information to webscrape information from

In [5]:
trips=pd.read_csv('trips.txt') # Lists all trips by route with destination sign for each
routes=pd.read_csv('routes.txt')# Lists route names
stop_times=pd.read_csv('stop_times.txt')# Contains a list of stops by routes, by trip, with their individual stop times
stops=pd.read_csv('stops.txt')# Lists stops with their individual latitude and longitude
shapes=pd.read_csv('shapes.txt')# Contains information for route traces
calendar=pd.read_csv('calendar.txt') # Dates - Lists dates when MDT routes operate in holiday schedule
# Cleaning Data sets
trips=trips.drop(['trip_short_name','wheelchair_accessible','bikes_allowed'],axis=1)
routes=routes.drop(['agency_id','route_desc','route_url','route_text_color'],axis=1)
stop_times=stop_times.drop(['stop_headsign'],axis=1)
stops=stops.drop(['zone_id','stop_url','location_type','parent_station','stop_timezone','wheelchair_boarding','stop_desc'],axis=1)

In [28]:
trips.head(100)

,route_id,service_id,trip_id,trip_headsign,direction_id,block_id,shape_id
0,21358,1,4363650,1 - SW 168 St,0,1338419,164141
1,21358,1,4363658,1 - SW 168 St,0,1338418,164141
2,21358,1,4363649,1 - SW 168 St,0,1338419,164141
3,21358,1,4363656,1 - SW 168 St,0,1338418,164141
4,21358,1,4363648,1 - SW 168 St,0,1338419,164141
5,21358,1,4363655,1 - SW 168 St,0,1338418,164141
6,21358,1,4363647,1 - SW 168 St,0,1338419,164141
7,21358,1,4363640,1 - SW 168 St,0,1338418,164141
8,21358,1,4363646,1 - SW 168 St,0,1338419,164141
9,21358,1,4363654,1 - SW 168 St,0,1338418,164141
10,21358,1,4363645,1 - SW 168 St,0,1338419,164141
11,21358,1,4363657,1 - SW 168 St,0,1338418,164141
12,21358,1,4363644,1 - SW 168 St,0,1338419,164141
13,21358,1,4363653,1 - SW 168 St,0,1338418,164141
14,21358,1,4363643,1 - SW 168 St,0,1338419,164141
15,21358,1,4363652,1 - SW 168 St,0,1338418,164141
16,21358,1,4363642,1 - SW 168 St,0,1338419,164141
17,21358,1,4363651,1 - SW 168 St,0,1338418,164141
18,21358,1,4363659,1 - SW 168 St,0,1338419,164141
19,21358,1,4363641,1 - SW 168 St,0,1338418,164141
20,21358,1,4363661,1 - South Miami Heights,1,1338419,164142
21,21358,1,4363677,1 - South Miami Heights,1,1338418,164142
22,21358,1,4363668,1 - South Miami Heights,1,1338419,164142
23,21358,1,4363676,1 - South Miami Heights,1,1338418,164142
24,21358,1,4363667,1 - South Miami Heights,1,1338419,164142
25,21358,1,4363675,1 - South Miami Heights,1,1338418,164142
26,21358,1,4363666,1 - South Miami Heights,1,1338419,164142
27,21358,1,4363674,1 - South Miami Heights,1,1338418,164142
28,21358,1,4363665,1 - South Miami Heights,1,1338419,164142
29,21358,1,4363673,1 - South Miami Heights,1,1338418,164142
...,...,...,...,...,...,...,...
70,21359,1,4363766,10 - Omni,0,1341935,164143
71,21359,1,4363816,10 - M. Gdns Dr / NE 19 Ave,1,1338429,164145
72,21359,1,4363796,10 - M. Gdns Dr / NE 19 Ave,1,1338426,164145
73,21359,1,4363815,10 - M. Gdns Dr / NE 19 Ave,1,1338427,164145
74,21359,1,4363814,10 - M. Gdns Dr / NE 19 Ave,1,1338425,164145
75,21359,1,4363819,10 - M. Gdns Dr / NE 19 Ave,1,1338424,164145
76,21359,1,4363795,10 - M. Gdns Dr / NE 19 Ave,1,1338429,164145
77,21359,1,4363794,10 - M. Gdns Dr / NE 19 Ave,1,1338428,164145
78,21359,1,4363805,10 - M. Gdns Dr / NE 19 Ave,1,1338426,164145
79,21359,1,4363813,10 - M. Gdns Dr / NE 19 Ave,1,1341934,164145
80,21359,1,4363812,10 - M. Gdns Dr / NE 19 Ave,1,1338425,164145
81,21359,1,4363811,10 - M. Gdns Dr / NE 19 Ave,1,1338424,164145
82,21359,1,4363793,10 - M. Gdns Dr / NE 19 Ave,1,1338429,164145
83,21359,1,4363804,10 - M. Gdns Dr / NE 19 Ave,1,1341936,164145
84,21359,1,4363801,10 - M. Gdns Dr / NE 19 Ave,1,1338426,164145
85,21359,1,4363800,10 - M. Gdns Dr / NE 19 Ave,1,1341934,164145
86,21359,1,4363810,10 - M. Gdns Dr / NE 19 Ave,1,1338425,164145
87,21359,1,4363803,10 - M. Gdns Dr / NE 19 Ave,1,1338424,164145
88,21359,1,4363792,10 - M. Gdns Dr / NE 19 Ave,1,1341929,164145
89,21359,1,4363791,10 - M. Gdns Dr / NE 19 Ave,1,1341936,164145
90,21359,1,4363809,10 - M. Gdns Dr / NE 19 Ave,1,1341931,164145
91,21359,1,4363818,10 - M. Gdns Dr / NE 19 Ave,1,1341934,164145
92,21359,1,4363790,10 - M. Gdns Dr / NE 19 Ave,1,1341932,164145
93,21359,1,4363823,10 - M. Gdns Dr / NE 19 Ave,1,1341933,164145
94,21359,1,4363822,10 - M. Gdns Dr / NE 19 Ave,1,1341930,164145
95,21359,1,4363808,10 - M. Gdns Dr / NE 19 Ave,1,1341936,164145
96,21359,1,4363802,10 - M. Gdns Dr / NE 19 Ave,1,1341931,164145
97,21359,1,4363821,10 - M. Gdns Dr / NE 19 Ave,1,1341935,164145
98,21359,1,4363806,10 - M. Gdns Dr / NE 19 Ave,1,1341932,164145
99,21359,1,4363807,10 - M. Gdns Dr / NE 19 Ave,1,1341933,164145

In [7]:
routes.head()

,route_id,route_short_name,route_long_name,route_type,route_color
0,21358,1,SO.MIAMI HTS-PERRINE VIA SOUTHLAND,3,FF00FF
1,21387,2,DOWNTOWN-163 ST MALL VIA NW 2 AVE,3,008000
2,21416,3,AVENTURA-DOWNTOWN VIA BISC.BLVD.,3,800080
3,21440,7,DOWNTOWN-DOLPH MALL/AIRPORT VIA 7ST,3,FF0000
4,21447,8,BRICKELL-107AV/WSTCHSTR VIA SW 8 ST,3,800000

In [8]:
stop_times.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,shape_dist_traveled
0,4363640,11:15:00,11:15:00,1,1,0,0,NaN
1,4363640,11:15:29,11:15:29,3614,2,0,0,0.1548
2,4363640,11:16:07,11:16:07,3213,3,0,0,0.3540
3,4363640,11:16:43,11:16:43,3214,4,0,0,0.5445
4,4363640,11:18:16,11:18:16,3621,5,0,0,1.0269

In [9]:
print(stop_times['stop_id'].unique())

[    1  3614  3213 ... 10993 10994 10995]

In [10]:
stops.head()

   stop_id stop_code                   stop_name   stop_lat   stop_lon
0        1  115AQRSN  SW 114 AV & QUAIL ROOST DR  25.592446 -80.377954
1        2  CTLRTERW  SW 211 ST & SOUTHLAND MALL  25.571929 -80.366647
2        3  SHCTPERN            US 1 & SW 174 ST  25.608124 -80.347631
3        4  152SBSWN          BUSWAY & SW 152 ST  25.628291 -80.341621
4        5  136SBSWN          BUSWAY & SW 136 ST  25.644519 -80.334092

In [11]:
print(stops['stop_id'].unique())

[    1     2     3 ... 11238 11239 11240]

In [12]:
shapes.head()

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
0,164141,25.592615,-80.378586,1,0.0000
1,164141,25.591776,-80.379684,2,0.1440
2,164141,25.591535,-80.380010,3,0.1867
3,164141,25.591209,-80.380449,4,0.2435
4,164141,25.590993,-80.380741,5,0.2820

In [13]:
calendar.head()

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,1,1,1,1,1,1,0,0,20190630,20191116
1,2,0,0,0,0,0,1,0,20190630,20191116
2,3,0,0,0,0,0,0,1,20190630,20191116
3,6,1,1,1,1,1,0,0,20190324,20191116
4,7,0,0,0,0,0,1,0,20190324,20191116

In [30]:
stop_new= pd.merge(stop_times,stops,on='stop_id')
stop_new

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,shape_dist_traveled,stop_code,stop_name,stop_lat,stop_lon
0,4363640,11:15:00,11:15:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
1,4363641,19:15:00,19:15:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
2,4363642,17:15:00,17:15:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
3,4363643,15:55:00,15:55:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
4,4363644,14:35:00,14:35:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
5,4363645,13:15:00,13:15:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
6,4363646,11:55:00,11:55:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
7,4363647,10:35:00,10:35:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
8,4363648,9:15:00,9:15:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
9,4363649,7:55:00,7:55:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
10,4363650,6:35:00,6:35:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
11,4363651,17:55:00,17:55:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
12,4363652,16:35:00,16:35:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
13,4363653,15:15:00,15:15:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
14,4363654,12:35:00,12:35:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
15,4363655,9:55:00,9:55:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
16,4363656,8:35:00,8:35:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
17,4363657,13:55:00,13:55:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
18,4363658,7:15:00,7:15:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
19,4363659,18:35:00,18:35:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
20,4363661,7:44:00,7:44:00,1,31,0,0,11.7083,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
21,4363665,13:05:00,13:05:00,1,31,0,0,11.7083,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
22,4363666,11:45:00,11:45:00,1,31,0,0,11.7083,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
23,4363667,10:25:00,10:25:00,1,31,0,0,11.7083,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
24,4363668,9:06:00,9:06:00,1,31,0,0,11.7083,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
25,4363673,13:45:00,13:45:00,1,31,0,0,11.7083,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
26,4363674,12:25:00,12:25:00,1,31,0,0,11.7083,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
27,4363675,11:05:00,11:05:00,1,31,0,0,11.7083,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
28,4363676,9:45:00,9:45:00,1,31,0,0,11.7083,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
29,4363677,8:24:00,8:24:00,1,31,0,0,11.7083,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954
...,...,...,...,...,...,...,...,...,...,...,...,...
899926,3818617,12:21:15,12:21:15,10988,8,0,0,6.5635,PALRTA07,SW 144 ST@US1,25.636659,-80.337694
899927,3818618,13:22:04,13:22:04,10988,8,0,0,6.5635,PALRTA07,SW 144 ST@US1,25.636659,-80.337694
899928,3818615,10:23:12,10:23:12,10989,9,0,0,7.1681,PALRTA08,PUBLIX SHOPPING PLAZA@SW 146 ST,25.633782,-80.336887
899929,3818616,11:23:12,11:23:12,10989,9,0,0,7.1681,PALRTA08,PUBLIX SHOPPING PLAZA@SW 146 ST,25.633782,-80.336887
899930,3818617,12:23:12,12:23:12,10989,9,0,0,7.1681,PALRTA08,PUBLIX SHOPPING PLAZA@SW 146 ST,25.633782,-80.336887
899931,3818618,13:24:06,13:24:06,10989,9,0,0,7.1681,PALRTA08,PUBLIX SHOPPING PLAZA@SW 146 ST,25.633782,-80.336887
899932,3818615,10:25:32,10:25:32,10213,10,0,0,7.8890,152SBSWY,SW 152 ST BUSWAY STATION,25.629805,-80.341149
899933,3818616,11:25:32,11:25:32,10213,10,0,0,7.8890,152SBSWY,SW 152 ST BUSWAY STATION,25.629805,-80.341149
899934,3818617,12:25:32,12:25:32,10213,10,0,0,7.8890,152SBSWY,SW 152 ST BUSWAY STATION,25.629805,-80.341149
899935,3818618,13:26:31,13:26:31,10213,10,0,0,7.8890,152SBSWY,SW 152 ST BUSWAY STATION,25.629805,-80.341149
899936,3818615,10:30:53,10:30:53,10991,12,0,0,9.5442,PALRTA10,SW 152 ST@SW 82 AV,25.629243,-80.325691
899937,3818616,11:30:53,11:30:53,10991,12,0,0,9.5442,PALRTA10,SW 152 ST@SW 82 AV,25.629243,-80.325691
899938,3818617,12:30:53,12:30:53,10991,12,0,0,9.5442,PALRTA10,SW 152 ST@SW 82 AV,25.629243,-80.325691
899939,3818618,13:32:05,13:32:05,10991,12,0,0,9.5442,PALRTA10,SW 152 ST@SW 82 AV,25.629243,-80.325691
899940,3818615,10:36:09,10:36:09,10992,13,0,0,11.1708,PALRTA11,SW 168 ST@SW 82 AV,25.614749,-80.324718
899941,3818616,11:36:09,11:36:09,10992,13,0,0,11.1708,PALRTA11,SW 168 ST@SW 82 AV,25.614749,-80.324718
899942,3818617,12:36:09,12:36:09,10992,13,0,0,11.1708,PALRTA11,SW 168 ST@SW 82 AV,25.614749,-80.324718
899943,3818618,13:37:33,13:37:33,10992,13,0,0,11.1708,PALRTA11,SW 168 ST@SW 82 AV,25.614749,-80.324718
899944,3818615,10:38:49,10:38:49,10993,14,0,0,11.9965,PALRTA12,SW 168 ST@SW 87 AV,25.614476,-80.332489
899945,3818616,11:38:49,11:38:49,10993,14,0,0,11.9965,PALRTA12,SW 168 ST@SW 87 AV,25.614476,-80.332489
899946,3818617,12:38:49,12:38:49,10993,14,0,0,11.9965,PALRTA12,SW 168 ST@SW 87 AV,25.614476,-80.332489
899947,3818618,13:40:19,13:40:19,10993,14,0,0,11.9965,PALRTA12,SW 168 ST@SW 87 AV,25.614476,-80.332489
899948,3818615,10:41:32,10:41:32,10994,15,0,0,12.8372,PALRTA13,SW 168 ST@SW 92 AV,25.614263,-80.340766
899949,3818616,11:41:32,11:41:32,10994,15,0,0,12.8372,PALRTA13,SW 168 ST@SW 92 AV,25.614263,-80.340766
899950,3818617,12:41:32,12:41:32,10994,15,0,0,12.8372,PALRTA13,SW 168 ST@SW 92 AV,25.614263,-80.340766
899951,3818618,13:43:08,13:43:08,10994,15,0,0,12.8372,PALRTA13,SW 168 ST@SW 92 AV,25.614263,-80.340766
899952,3818615,10:47:00,10:47:00,10995,16,0,0,14.4884,PALRTA14,SW 176 ST@SW 94 AV,25.606451,-80.344420
899953,3818616,11:47:00,11:47:00,10995,16,0,0,14.4884,PALRTA14,SW 176 ST@SW 94 AV,25.606451,-80.344420
899954,3818617,12:47:00,12:47:00,10995,16,0,0,14.4884,PALRTA14,SW 176 ST@SW 94 AV,25.606451,-80.344420
899955,3818618,13:49:00,13:49:00,10995,16,0,0,14.5438,PALRTA14,SW 176 ST@SW 94 AV,25.606451,-80.344420

In [15]:
trip_stop=pd.merge(stop_new,trips,on='trip_id')
trip_stop.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,shape_dist_traveled,stop_code,stop_name,stop_lat,stop_lon,route_id,service_id,trip_headsign,direction_id,block_id,shape_id
0,4363640,11:15:00,11:15:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954,21358,1,1 - SW 168 St,0,1338418,164141
1,4363640,11:15:29,11:15:29,3614,2,0,0,0.1548,QRSD17A3,QUAIL ROOST DR & SW 117 AV,25.591811,-80.379838,21358,1,1 - SW 168 St,0,1338418,164141
2,4363640,11:16:07,11:16:07,3213,3,0,0,0.3540,C117QUA4,SW 117 AV & QUAIL ROOST DR,25.590333,-80.380733,21358,1,1 - SW 168 St,0,1338418,164141
3,4363640,11:16:43,11:16:43,3214,4,0,0,0.5445,C1171923,SW 117 AV & SW 192 ST,25.588605,-80.380631,21358,1,1 - SW 168 St,0,1338418,164141
4,4363640,11:18:16,11:18:16,3621,5,0,0,1.0269,C19213B6,SW 192 ST & SW 113 PL,25.588389,-80.376020,21358,1,1 - SW 168 St,0,1338418,164141

In [16]:
trips_stop_routes=pd.merge(trip_stop,routes,on='route_id')

In [17]:
trips_stops_routes_calendar=pd.merge(trips_stop_routes,calendar,on='service_id')

In [18]:
shapes.dtypes

shape_id                 int64
shape_pt_lat           float64
shape_pt_lon           float64
shape_pt_sequence        int64
shape_dist_traveled    float64
dtype: object

In [19]:
trips.dtypes

route_id          int64
service_id        int64
trip_id           int64
trip_headsign    object
direction_id      int64
block_id          int64
shape_id          int64
dtype: object

In [24]:
pd.set_option('display.max_columns',100)
trips_stops_routes_calendar.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,shape_dist_traveled,stop_code,stop_name,stop_lat,stop_lon,route_id,service_id,trip_headsign,direction_id,block_id,shape_id,route_short_name,route_long_name,route_type,route_color,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,4363640,11:15:00,11:15:00,1,1,0,0,NaN,115AQRSN,SW 114 AV & QUAIL ROOST DR,25.592446,-80.377954,21358,1,1 - SW 168 St,0,1338418,164141,1,SO.MIAMI HTS-PERRINE VIA SOUTHLAND,3,FF00FF,1,1,1,1,1,0,0,20190630,20191116
1,4363640,11:15:29,11:15:29,3614,2,0,0,0.1548,QRSD17A3,QUAIL ROOST DR & SW 117 AV,25.591811,-80.379838,21358,1,1 - SW 168 St,0,1338418,164141,1,SO.MIAMI HTS-PERRINE VIA SOUTHLAND,3,FF00FF,1,1,1,1,1,0,0,20190630,20191116
2,4363640,11:16:07,11:16:07,3213,3,0,0,0.3540,C117QUA4,SW 117 AV & QUAIL ROOST DR,25.590333,-80.380733,21358,1,1 - SW 168 St,0,1338418,164141,1,SO.MIAMI HTS-PERRINE VIA SOUTHLAND,3,FF00FF,1,1,1,1,1,0,0,20190630,20191116
3,4363640,11:16:43,11:16:43,3214,4,0,0,0.5445,C1171923,SW 117 AV & SW 192 ST,25.588605,-80.380631,21358,1,1 - SW 168 St,0,1338418,164141,1,SO.MIAMI HTS-PERRINE VIA SOUTHLAND,3,FF00FF,1,1,1,1,1,0,0,20190630,20191116
4,4363640,11:18:16,11:18:16,3621,5,0,0,1.0269,C19213B6,SW 192 ST & SW 113 PL,25.588389,-80.376020,21358,1,1 - SW 168 St,0,1338418,164141,1,SO.MIAMI HTS-PERRINE VIA SOUTHLAND,3,FF00FF,1,1,1,1,1,0,0,20190630,20191116

In [21]:
# trips_stops_routes_calendar_shape=pd.merge(trips_stops_routes_calendar,shapes,on='shape_id')

In [25]:
shapes.shape_id.nunique()

460

In [29]:
pd.merge(shapes,trips,on='shape_id')

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled,route_id,service_id,trip_id,trip_headsign,direction_id,block_id
0,164141,25.592615,-80.378586,1,0.0000,21358,1,4363650,1 - SW 168 St,0,1338419
1,164141,25.592615,-80.378586,1,0.0000,21358,1,4363658,1 - SW 168 St,0,1338418
2,164141,25.592615,-80.378586,1,0.0000,21358,1,4363649,1 - SW 168 St,0,1338419
3,164141,25.592615,-80.378586,1,0.0000,21358,1,4363656,1 - SW 168 St,0,1338418
4,164141,25.592615,-80.378586,1,0.0000,21358,1,4363648,1 - SW 168 St,0,1338419
5,164141,25.592615,-80.378586,1,0.0000,21358,1,4363655,1 - SW 168 St,0,1338418
6,164141,25.592615,-80.378586,1,0.0000,21358,1,4363647,1 - SW 168 St,0,1338419
7,164141,25.592615,-80.378586,1,0.0000,21358,1,4363640,1 - SW 168 St,0,1338418
8,164141,25.592615,-80.378586,1,0.0000,21358,1,4363646,1 - SW 168 St,0,1338419
9,164141,25.592615,-80.378586,1,0.0000,21358,1,4363654,1 - SW 168 St,0,1338418
10,164141,25.592615,-80.378586,1,0.0000,21358,1,4363645,1 - SW 168 St,0,1338419
11,164141,25.592615,-80.378586,1,0.0000,21358,1,4363657,1 - SW 168 St,0,1338418
12,164141,25.592615,-80.378586,1,0.0000,21358,1,4363644,1 - SW 168 St,0,1338419
13,164141,25.592615,-80.378586,1,0.0000,21358,1,4363653,1 - SW 168 St,0,1338418
14,164141,25.592615,-80.378586,1,0.0000,21358,1,4363643,1 - SW 168 St,0,1338419
15,164141,25.592615,-80.378586,1,0.0000,21358,1,4363652,1 - SW 168 St,0,1338418
16,164141,25.592615,-80.378586,1,0.0000,21358,1,4363642,1 - SW 168 St,0,1338419
17,164141,25.592615,-80.378586,1,0.0000,21358,1,4363651,1 - SW 168 St,0,1338418
18,164141,25.592615,-80.378586,1,0.0000,21358,1,4363659,1 - SW 168 St,0,1338419
19,164141,25.592615,-80.378586,1,0.0000,21358,1,4363641,1 - SW 168 St,0,1338418
20,164141,25.592615,-80.378586,1,0.0000,21358,2,4363678,1 - SW 168 St,0,1338420
21,164141,25.592615,-80.378586,1,0.0000,21358,2,4363696,1 - SW 168 St,0,1338421
22,164141,25.592615,-80.378586,1,0.0000,21358,2,4363690,1 - SW 168 St,0,1338420
23,164141,25.592615,-80.378586,1,0.0000,21358,2,4363695,1 - SW 168 St,0,1338421
24,164141,25.592615,-80.378586,1,0.0000,21358,2,4363689,1 - SW 168 St,0,1338420
25,164141,25.592615,-80.378586,1,0.0000,21358,2,4363694,1 - SW 168 St,0,1338421
26,164141,25.592615,-80.378586,1,0.0000,21358,2,4363688,1 - SW 168 St,0,1338420
27,164141,25.592615,-80.378586,1,0.0000,21358,2,4363693,1 - SW 168 St,0,1338421
28,164141,25.592615,-80.378586,1,0.0000,21358,2,4363685,1 - SW 168 St,0,1338420
29,164141,25.592615,-80.378586,1,0.0000,21358,2,4363692,1 - SW 168 St,0,1338421
...,...,...,...,...,...,...,...,...,...,...,...
6457782,159571,25.629385,-80.316614,96,8.9388,20408,1,4224926,Village of Palmetto Bay to Park & Ride,1,21504
6457783,159571,25.629385,-80.316614,96,8.9388,20408,1,4224927,Village of Palmetto Bay to Park & Ride,1,21505
6457784,159571,25.629385,-80.316614,96,8.9388,20408,1,4224928,Village of Palmetto Bay to Park & Ride,1,21506
6457785,159571,25.629385,-80.316614,96,8.9388,20408,1,4224929,Village of Palmetto Bay to Park & Ride,1,21507
6457786,159571,25.629385,-80.316614,96,8.9388,20408,1,4224930,Village of Palmetto Bay to Park & Ride,1,21508
6457787,159571,25.629385,-80.316614,96,8.9388,20408,1,4224931,Village of Palmetto Bay to Park & Ride,1,21509
6457788,159571,25.629385,-80.316614,96,8.9388,20408,1,4224932,Village of Palmetto Bay to Park & Ride,1,21510
6457789,159571,25.629385,-80.316614,96,8.9388,20408,1,4224933,Village of Palmetto Bay to Park & Ride,1,21511
6457790,159571,25.629385,-80.316614,96,8.9388,20408,1,4224934,Village of Palmetto Bay to Park & Ride,1,21512
6457791,159571,25.629385,-80.316614,96,8.9388,20408,1,4224935,Village of Palmetto Bay to Park & Ride,1,21513
6457792,159571,25.629321,-80.316605,97,8.9459,20408,1,4224926,Village of Palmetto Bay to Park & Ride,1,21504
6457793,159571,25.629321,-80.316605,97,8.9459,20408,1,4224927,Village of Palmetto Bay to Park & Ride,1,21505
6457794,159571,25.629321,-80.316605,97,8.9459,20408,1,4224928,Village of Palmetto Bay to Park & Ride,1,21506
6457795,159571,25.629321,-80.316605,97,8.9459,20408,1,4224929,Village of Palmetto Bay to Park & Ride,1,21507
6457796,159571,25.629321,-80.316605,97,8.9459,20408,1,4224930,Village of Palmetto Bay to Park & Ride,1,21508
6457797,159571,25.629321,-80.316605,97,8.9459,20408,1,4224931,Village of Palmetto Bay to Park & Ride,1,21509
6457798,159571,25.629321,-80.316605,97,8.9459,20408,1,4224932,Village of Palmetto Bay to Park & Ride,1,21510
6457799,159571,25.629321,-80.316605,97,8.9459,20408,1,4224933,Village of Palmetto Bay to Park & Ride,1,21511
6457800,159571,25.629321,-80.316605,97,8.9459,20408,1,4224934,Village of Palmetto Bay to Park & Ride,1,21512
6457801,159571,25.629321,-80.316605,97,8.9459,20408,1,4224935,Village of Palmetto Bay to Park & Ride,1,21513
6457802,159571,25.629327,-80.316280,98,8.9789,20408,1,4224926,Village of Palmetto Bay to Park & Ride,1,21504
6457803,159571,25.629327,-80.316280,98,8.9789,20408,1,4224927,Village of Palmetto Bay to Park & Ride,1,21505
6457804,159571,25.629327,-80.316280,98,8.9789,20408,1,4224928,Village of Palmetto Bay to Park & Ride,1,21506
6457805,159571,25.629327,-80.316280,98,8.9789,20408,1,4224929,Village of Palmetto Bay to Park & Ride,1,21507
6457806,159571,25.629327,-80.316280,98,8.9789,20408,1,4224930,Village of Palmetto Bay to Park & Ride,1,21508
6457807,159571,25.629327,-80.316280,98,8.9789,20408,1,4224931,Village of Palmetto Bay to Park & Ride,1,21509
6457808,159571,25.629327,-80.316280,98,8.9789,20408,1,4224932,Village of Palmetto Bay to Park & Ride,1,21510
6457809,159571,25.629327,-80.316280,98,8.9789,20408,1,4224933,Village of Palmetto Bay to Park & Ride,1,21511
6457810,159571,25.629327,-80.316280,98,8.9789,20408,1,4224934,Village of Palmetto Bay to Park & Ride,1,21512
6457811,159571,25.629327,-80.316280,98,8.9789,20408,1,4224935,Village of Palmetto Bay to Park & Ride,1,21513